# Generated by Django 5.2.4 on 2025-07-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
