# Generated by Django 5.2.4 on 2025-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='box',
            field=models.IntegerField(choices=[(1, 'Box 1'), (2, 'Box 2'), (3, 'Box 3')], default=1),
        ),
    ]
